### ISSUE TITLE
The NTP Server IP input box is too small to display on SID160

### ISSUE THREAD

**Issue by donald-sick** [SICKAppSpaceCodingStarterKit/CSK_Module_DateTime#3]
As a user, I want to edit all data on date time UI on any reasonable resolution. When it displays on SID160 screen, the NTP server IP input box can see only one digit. No matter the left navigation bar is hidden or not.

**CSK module:**
 - Version: 3.0.0, should be the same for 3.1.0

**AppSpace device used:**
 - SIM2500
 - SID160, 1366*768
 
**To Reproduce**  
1. Go to DateTime UI on SID160 screen

**Expected behavior**  
Should be able to see whole IP xxx.xxx.xxx.xxx

**Screenshots**  
![image](https://github.com/SICKAppSpaceCodingStarterKit/CSK_Module_DateTime/assets/162647566/f3ccf184-b210-4764-9542-6e58f34f083e)

**Additional Info**
It displays properly when x resolution is wider than 1660. So on site, user has to use a separate PC to connect to SIM2500 to change the setting.

**Comment by golluroSICKAG** [comment]
Please check this PR and give response if this fixes your issue:
https://github.com/SICKAppSpaceCodingStarterKit/CSK_Module_DateTime/pull/4

**Comment by donald-sick** [comment]
It is fixed. Thanks for the quick response.
